//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lotz_PSD_LEC_AoL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartID { get; set; }
        public int CustomerID { get; set; }
        public int ClothID { get; set; }
        public int Qty { get; set; }
        public int Price { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
